### ISSUE TITLE
Connecting your firebase front-end to www.846policebrutality.com

### ISSUE THREAD

**Issue by 949mac** [mnlmaier/846-frontend#1]
Interested? You might need to make a few tweaks to the config in Firebase. From there, I'll need some DNS info.

Let me know, and I'll patch it through. 

Front-end looks great, btw.

**Comment by mnlmaier** [comment]
Sure, what exactly do you need?

**Comment by 949mac** [comment]
In Hosting:

* Add a custom domain with value `846policebrutality.com` and `www.846policebrutality.com`
* Then give me the TXT record

![image](https://user-images.githubusercontent.com/23151962/83912839-5fbae800-a723-11ea-8b8b-381e4b61c4a8.png)

![image](https://user-images.githubusercontent.com/23151962/83912936-8c6eff80-a723-11ea-9168-d91db41b2fae.png)

Thanks!

**Comment by mnlmaier** [comment]
`google-site-verification=vL70_3ND6_Z3pbPRYiJYgJuGoTSRkC_tPtyRvaLfuF4`

**Comment by 949mac** [comment]
This has been completed. Let me know if you see any issues on your end. It might take a little while depending on how quickly firebase checks.

But here's a screenshot showing the record has resolved publicly.

![image](https://user-images.githubusercontent.com/23151962/83945518-fb9a3180-a7bf-11ea-823e-79458f7548ce.png)
