### ISSUE TITLE
Suggested textual change for frontpage of 2020policeprutality.com: riots --> protests

### ISSUE THREAD

**Issue by FrankvanCaspel** [mnlmaier/846-frontend#11]
On the frontpage of 2020policebrutality.com it currently says:

"This interactive map showcases incidents with police enforcing unecessary actions against protesters during the Riots after the murder of George Floyd."

I'd suggest removing the typo in 'unecessary' and changing 'Riots' (capital R?) to 'protests'. Naming them 'riots' undercuts the idea that police enforcement is unnecessary. To prevent having 'protest' twice in then sentence I'd then also suggest replacing 'protesters' with 'citizens'. Like so:

"This interactive map showcases incidents with police enforcing unnecessary actions against citizens during the protests after the murder of George Floyd."

**Comment by mnlmaier** [comment]
thanks for the suggestion and thanks @rsarvar1a for taking care of it! :)
