### ISSUE TITLE
Adding video to the front-end

### ISSUE THREAD

**Issue by 949mac** [mnlmaier/846-frontend#2]
Any plans to add video? I've got 166 videos (mostly mp4 format) added to the API. 

I aggregated the videos using a custom method/api, so the content should be streamable from the direct hosts using the links in the API.

https://api.846policebrutality.com/api/incidents?include=evidence

Then `data.evidence.video.streams` is what you want to look for.

Edit: I revised the API endpoint linked above. Previously this post was pointing to a staging url.

**Comment by bobnearents** [comment]
I was thinking that we could have a link in the marker's infowindow that takes the user to an 'incident page' where they can get more information on the specific incident. I think that would be a good place to stream any videos of the incident we might have.

**Comment by mnlmaier** [comment]
@bobnearents would it make sense to use the sidebar for incident information? playing the video in the sidebar header and having tweets/content underneath. would also make it possible to navigate through incidents using forward » and backwards « buttons in the sidebar while highlighting the currently active incident.

we could store the active incident id in the Vuex store to that every single component can access and react to it.

wdyt?

**Comment by bobnearents** [comment]
I like that idea. That gives immediate access to all the information.
If we do navigate between incidents in the sidebar, i think it should also highlight and center on the relevant marker. 

This is my first time with Vue so I'm going slow, and let me know if I make any stupid mistakes. 😅

https://github.com/mnlmaier/846-frontend/pull/5 
This updates state per your first idea. can we have the sidebar listen to state and update content accordingly?

**Comment by mnlmaier** [comment]
Started implementing the sidebar thing :) @bobnearents which code editor are you on? It seems like some stuff got through the pre commit linter, would make live easier if formatting errors will be catched before committing. cleaned that up a bit but don't worry, nbd!

**Comment by 949mac** [comment]
Terrific. Keep it up guys.
