### ISSUE TITLE
Markers that share an exact location are not inspectable

### ISSUE THREAD

**Issue by rsarvar1a** [mnlmaier/846-frontend#3]
Example: the incidents in Denver:
![](https://user-images.githubusercontent.com/45308543/83872437-faa1cb00-a6ff-11ea-8091-0f64bda6871b.png)

We could possibly add some noise to the actual lat/long coordinates so that the markers become distinguishable at a given zoom threshold? I can take a look at it.

**Comment by mnlmaier** [comment]
Thanks! :) Good idea. We might want to implement this on backend side aswell @949mac
