### ISSUE TITLE
Marker info window should close when clicked outside

### ISSUE THREAD

**Issue by bobnearents** [mnlmaier/846-frontend#6]
we should update this so info windows close when we click anywhere else on the map. That way the map doesn't get clogged with a bunch of windows

**Comment by mnlmaier** [comment]
we could also allow only one opened marker window at a time

**Comment by rsarvar1a** [comment]
In #7 we removed the InfoWindows completely. However, the issue is still sort of relevant.

When a marker is active, there should be a way to deactivate the marker (by clicking the map, maybe?) to return the sidebar to the CTA/info view.
